#!/bin/bash

clear

cd /home/SHOP/kalatori-js

export KALATORI_HOST="0.0.0.0:16736"
export KALATORI_SEED="@@@@@@@@@@@@@@@"
#export KALATORI_DESTINATION="5EqPxC7iRP6vQTsg9rwXNHsA7VqbZa7uBjj7P4YqjTvfLiiJ"
export KALATORI_DESTINATION="1sa1P9pU4Pa6JM2nyB2vcAQw9cCxttzpovAmCwcUHZ6UxET"
export KALATORI_REMARK="DEBUG=true;Ebala=1;public=yes"

/usr/bin/node /home/SHOP/kalatori-js/daemon.js


